FROM alpine:3.20
WORKDIR /app
RUN adduser -D -H appuser && apk add --no-cache tzdata
COPY app/subscription-server /app/subscription-server
RUN chmod +x /app/subscription-server
COPY app/public /app/public
ENV APP_PORT=8080
EXPOSE 8080
USER appuser
CMD ["/app/subscription-server"]
